### PR TITLE
Add a button for keyboard lock

### PR DESCRIPTION
**Pull request by michaelwasserman**

### CODE REVIEW

**Comment by michaelwasserman** [comment]
Hey @engedy can you please take a look? Thanks!

**Comment by engedy** [comment]
Sorry for missing this. This LGTM overall. I was thinking about making the button green to indicate success, but the Promise is returned async-immediately, and there does not seem to be any event to monitor to learn the lock took effect?

**Comment by michaelwasserman** [comment]
Thanks for the review!

> I was thinking about making the button green to indicate success, but the Promise is returned async-immediately, and there does not seem to be any event to monitor to learn the lock took effect?

Right, AFAICT, the promise can resolve even before it takes effect, i.e. when called before entering fullscreen.
I don't see a direct way to check if the lock is taking practical effect.

**Comment by michaelwasserman** [comment]
Maybe it's still useful to add feature detection and mark the button red/green on promise resolve/reject? I'll try to send another PR soon.

**Pull request merged**
