### PR TITLE
Add support for Web NFC

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR is about adding support for Web NFC so that web developers can play with the upcoming interstitial prompt.

Live preview is available at http://beaufortfrancois.github.io/permission.site/

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
FYI @zolkis @kenchris

**Comment by kenchris** [comment]
@rijubrata if the permission prompt is different for reader and writer (what did we settle on) maybe we need both

**Comment by beaufortfrancois** [comment]
For info, iOS has a "Ready to scan" text and a small customized text: ["the fire" below](https://github.com/alecdoconnor/iOS11-NFC/blob/58ed95ce9a3fdd3c533f5fdb53a8b4973656dcab/testingNFC/Info.plist#L6)

image

**Comment by riju** [comment]
Chrome UX and permission team (@engedy  and Namrata, cc: @reillyeon ) has given us feedback.

Current situation is we do not have to ask for prompt, but we need to show notification and usage indicators. For example in chrome flags enable quiet notification flag, go to permission.site and click notifications, it will show some notification and go away, but there will be a usage indicator beside the clock. From chrome://flags, choose the enable quieter notifications permissions prompt -> Enabled heads-up notification and by default for NFC it will be Allowed, with options to Block / Manage

Exact UI mockups and strings will be finalized by Namrata.

For the scope of Origin Trial for webNFC with ndef messages this is a solution we all can live with.
If we later, decide to add support for cards(transit passes, hotel doors) which follow another protocol, we will revisit the privacy and security situation.

**Comment by engedy** [comment]
Happy to approve a follow-up PR if we decide to go with separate permissions for read/write.

**Comment by beaufortfrancois** [comment]
@riju We may want to update this thread as it seems like we're going with permission prompt eventually.
Context: https://github.com/w3c/web-nfc/issues/425

**Pull request merged**
