### PR TITLE
Add button for the Serial API

### PR DESCRIPTION
**Pull request by reillyeon**
Specification: https://wicg.github.io/serial

As the WebUSB API has shipped I'm reusing the note about the experimental flag for this new API.

### CODE REVIEW

**Comment by reillyeon** [comment]
@beaufortfrancois

**Comment by beaufortfrancois** [comment]
Should `SerialPortRequestOptions` not be optional there so that web developers can write `navigator.serial.requestPort()` instead of `navigator.serial.requestPort({})`?

Otherwise LGTM

**Comment by reillyeon** [comment]
As with the `acceptAllDevices: true` parameter to bluetooth.requestDevice() we want to force developers to choose not to provide a filter explicitly. I've added the filter parameter here. Chromium currently doesn't enforce that it is present but soon will.

**Comment by beaufortfrancois** [comment]
@lgarron Can you merge?

**Comment by lgarron** [comment]
Looks like @dominickng merged!

Since we're successfully serving from GH Pages, that also takes care of deployment. :-D
Thanks for the PR!

**Pull request merged**
