### PR TITLE
Add support for XR (AR & VR)

### PR DESCRIPTION
**Pull request by beaufortfrancois**
This PR adds two buttons "Virtual Reality (VR)" and "Augmented Reality (AR)" so that people can try out XR permission prompts.

@mounirlamouri Did I miss anything?

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Note that I could have used `navigator.xr.requestSession('immersive-vr', { optionalFeatures: ['bounded-floor'] })` but it doesn't seem to make a difference in current Chrome canary for Android.

**Comment by mounirlamouri** [comment]
Should we only call `requestSession()` if `isSessionSupported()`? I guess we could grey out the button. Otherwise, LGTM. No need to worry about `bounded-floor`.

**Comment by beaufortfrancois** [comment]
This website is only for testing prompts. I don't think we need to disable buttons.
@engedy for thoughts

**Comment by engedy** [comment]
Yeah, just failing and coloring the button red (what the PR currently implements) sounds good to me.

**Comment by engedy** [comment]
Clarified with Francois that `requestSession()` is expected to properly reject if `!isSessionSupported()`, so current solution LGTM.

**Pull request merged**
