### PR TITLE
Change Bluetooth button to also connect to the device

### PR DESCRIPTION
**Pull request by g-ortuno**
Connecting to a Bluetooth device causes extra security UI to show up i.e. a tab indicator showing that we're currently connected to a device.

### CODE REVIEW

**Comment by g-ortuno** [comment]
fyi: This can be tested at https://rawgit.com/g-ortuno/permission.site/patch-1/index.html

**Comment by lgarron** [comment]
@beaufortfrancois, could you review for us?

@ericlaw1979 for Enamel review.

**Comment by beaufortfrancois** [comment]
LGTM.

Note that some bluetooth devices might not connect as bluetooth chooser could show non-connectable devices.

**Comment by ericlaw1979** [comment]
LGTM. I don't know who actually has permissions to merge this.

**Comment by lgarron** [comment]
> LGTM. I don't know who actually has permissions to merge this.

Could you check if you have permissions now?

**Comment by ericlaw1979** [comment]
Thanks, all!

**Comment by lgarron** [comment]
Deployed to production!

**Comment by g-ortuno** [comment]
Thanks for the reviews/pushing to prod!

**Pull request merged**
